### ISSUE TITLE
Main and Supporting files not shown on sidepanel on relationships tree view

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#5400] opened 2022-12-13 17:40 UTC
**Describe the bug**
While the main document and supporting files are shown in the sidepanel when clicking on a card, the same is NOT true when clicking on a relationship card on the templates.

Not sure why we still have the relationships sidepanel be a different component, but we either integrate them or we fix this so that it shows the missing metadata.

**Comment by Zasa-san** [comment] 2023-02-09 18:59
A bug where users could not switch between main documents when viewing a PDF has also been addressed in this PR.

This bug was caused by an `if` clause in

https://github.com/huridocs/uwazi/blob/37821e4d6bf3eab719ac78e79dff67ff936fe81f/app/react/Viewer/ViewerRoute.js#L42-L52

since it was returning false before it could check if the file had change.

**Comment by Zasa-san** [comment] 2023-02-09 19:01
The implementation for showing supporting files for related entities will only allow reading files (see/download/navigate to). Users will not be able to upload or modify files from this view.

**Closed as completed** 2023-02-10 14:07 UTC
Labels: Bug :lady_beetle:, Sprint, Priority: High, Frontend :sunglasses:
