### ISSUE TITLE
404 pages actually send a 200 status code [timeboxed 2 days]

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#6163] opened 2023-09-20 08:58 UTC
**Describe the bug**
When navigating to an url that does not exists the app properly redirects to a 404 page, but the status code sent is 200.

**To Reproduce**
1. Run uwazi
2. Go to localhost:3000/public/file_that_does_not_exists.txt
3. See a 404 page, and see on the browser console the actual status code being a 200

**Expected behavior**
Should return a 404 status code.

**Comment by fnocetti** [comment] 2023-10-09 15:15
I think there's a misconception regarding the handling of 404s. When a 404 is the correct answer to a request, the user should not be redirected to a 404, but the response of the interaction should be a 404. i.e the url shouldn't change, and there shouldn't be an extra navigation.

Edit: what I said looks like it's not the case for SSR resources. Maybe re-check for in-app navigation.

**Comment by RafaPolit** [comment] 2023-10-10 14:34
There are other inconsistencies: localhost:3000/wrongurl takes you to the homepage (at least on demo as currently configured).

Please look into the different possible 404s scenarios and fix them accordingly.  Report here which scenarios need addressing.

**Comment by fnocetti** [comment] 2023-11-20 14:24
The following cases were identified:
1. @RafaPolit 's : localhost:3000/wrongurl takes you to the homepage
2. Accessing non-existent routes that are not directly nested to the root, shows a 404 page but it returns a 200 code. _To be fixed by #6257_
3. Accessing a non-existent public file (as reported in this issue) reproduces the same issue as point 2, following the same mechanism. _To be fixed by #6257_
4. Accessing non existent entities or documents can fall into one of this cases:
  - If it is an in-app navigation, it will show an infinitely loading screen
  - If it is a direct url navigation, it will show a JSON message stating that the server got a 404. The request itself will return a code 500.

I didn't debug case 1.
Case 2 is related to the server-side rendering utility not returning any other code than a 200 when it gets to successfuly render a page. In this case, it's handled by the catch-all route, since there were no routes to properly handle the request. That catch-all renders a 404 error, but since it succesfully rendered, it will return a 200. A quick fix here is to make the utility return a 404 whenever the request is handled by a catch-all.
Case 3 is similar. It starts on the server. The static files middleware wont find the requested file and pass the responsibility to the next middleware. Since it's not a /api request, then it will go through the SSR flow and follow what happens in case 2.
Case 4 is related to missing implementation in the RouteHandler components. When they get a 404 from the server, the process will just fail. That means that:
- If it was an in-app navigation: there's no handling of the 404 receved, so the UI won't show accordingly,
- If it was a direct navigation: The SSR utility will fail with an unhandled exception, and therefore return a 500.

I will develop the quick fix for 2 and 3, that will fix what's reported in the issue. We should consider planning for the rest of the fixes.

**Closed as completed** 2024-01-29 17:52 UTC
Labels: Bug :lady_beetle:, Priority: High, Backend 💾
