### ISSUE TITLE
Activity log: Filter not working

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#6713] opened 2024-04-29 18:40 UTC
It seems the filter feature in the /settings/activitylog screen does not work:

- If you filter by user, it does work properly.
- If you filter by ids, methods, keywords, etc., it does NOT work, the result is always empty.
- Also, filtering by date (From..To) does NOT work too.

**Comment by mfacar** [comment] 2024-05-01 19:12
@salvalacruz, I tested it in uwazi.demo and checked that the filters are returning data for certain queries.  For example filtering by http methods like [POST, DELETE, PUT] or by a date range taking as reference the dates or records without filters. I also experience difficulties getting results because I believe filtering by URLs or keywords is expecting an exact match. Please can you check it? So we can have a better understanding of what the problem is.

**Comment by salvalacruz** [comment] 2024-05-02 12:54
Hi @mfacar, I create, edit and delete an entity in template "PERSONA" with title "ENTIDAD PRUEBA":
![image](https://github.com/huridocs/uwazi/assets/73410334/df9ba7da-f296-46bb-891a-1478ec20a7d7)

If I filter the activity log by user, the result is fine, but:

If I filter by "ENTIDAD PRUEBA", the result is empty (until some days ago, it was posible to search by entity titles):
![image](https://github.com/huridocs/uwazi/assets/73410334/009f343d-0442-4c0b-9ef1-37fef823cd26)

If I filter by date range, it does not seems it works:
![image](https://github.com/huridocs/uwazi/assets/73410334/773dc153-c630-48dd-be13-292509b0ce34)

Please let me know if you prefer to meet and we try together.
Thank you!

**Comment by serena-huridocs** [comment] 2024-05-02 13:31
This week's testing group's input: I tried to search by entity name in demo.uwazi.io and it did not work for me as well. Entering entity id to find the targeted actions did not help either. 

I suppose the persisting problem with dates will be fixed by this fix: https://github.com/huridocs/uwazi/pull/6667.

**Comment by salvalacruz** [comment] 2024-05-06 12:49
Activity log filtering is still NOT able to search by the title of entities.

cc @RafaPolit

**Comment by RafaPolit** [comment] 2024-05-06 13:47
The middle input filter is not working as the description lists. Yes, you can input Method, but then anything inside the body like Entity ID, or title, or any other value, would just yield nothing.

**Comment by fnocetti** [comment] 2024-05-06 15:02
A quick test shows that the GET request is being sent with every possible parameter set to the search term.
Because, particularly, `find` is set, it is generating this mongo query:
https://github.com/huridocs/uwazi/blob/42bb22fff1333679308b1be85bdd3c33274c0224/app/api/activitylog/activitylog.js#L40

Now, because also `method` is set, and is an array containing only the term, this happens later: 
https://github.com/huridocs/uwazi/blob/42bb22fff1333679308b1be85bdd3c33274c0224/app/api/activitylog/activitylog.js#L118

That must be generating a query like: 
```
{ $or: [...], method: { $in: [term] } }
```
which is likely not a valid mongo query (or in the best case it is looking for an `$or` field to be an array, which should return empty results).

That API definitively needs refactoring, but the fix is that the correct use of that endpoint, given the use case, is to only include the `find` parameter, plus the time related, pagination, and sort.
It looks like it may make the `username` filter stop working, that would need a backend fix.
cc @RafaPolit @mfacar

**Comment by mfacar** [comment] 2024-05-06 17:19
There are also some other problems with the search:
- The shown values don't correspond to the values filtered in the Mongo query. ie: 
   - Method UPDATE will never produce any results because the actual method is POST. We need to also support case insensitive search.
   - The description is parsed in the backend after making the request, adding more descriptive text not present in the database. We need to provide a result more compatible with the presented values.
   - We are searching for exact matches, wildcards are not supported.
- Sometimes the URL keeps the previous search params applied ignoring new filters changes 
- The changes in dates are affected by the previous point.

**Closed as completed** 2024-06-14 23:09 UTC
Labels: Bug :lady_beetle:, Priority: High
