### ISSUE TITLE
The "create password" process for new user fails

### ISSUE THREAD

**Issue by aphilop** [huridocs/uwazidocs#6834] opened 2024-05-29 11:48 UTC
**Describe the bug**
When a new user tries to create a password, the process fails. As a consequence, the user cannot login to their account.

**To Reproduce**
1. Create a new user
2. Open the link to create a password in the welcome email
3. Use the form to provide a password and click save

**Expected behavior**
The user must be able to create a password that can use to log in their account.

**Screenshots**

Error message

![image](https://github.com/huridocs/uwazi/assets/102693686/8a5ca13e-a9bd-4214-9be0-852bf52d535c)

**Device (please select all that apply)**
 - [x] Desktop
 - [ ] Mobile

**Browser**
Safari 17.5 on MacOS 12.7.5

**Comment by fnocetti** [comment] 2024-05-29 11:55
Thanks for the report @aphilop
This must be related to the recent hotfix. I'm taking care immediately.

**Comment by fnocetti** [comment] 2024-05-29 12:21
This not reproducible on the password recovery flow. That provides a workaround. The users can request a password recovery themselves to gain access to their account. I'm downgrading the severity.

As a side note, this is not reproducible in local/blank-state instances.

**Comment by fnocetti** [comment] 2024-05-29 12:28
In fact, I'm not longer able to reproduce this. May have it been a result of a race condition during today's deploy? Doesn't seem to make sense but I find no explanation.

@aphilop are you still experiencing this? If not, let's monitor the problem.

**Comment by aphilop** [comment] 2024-05-29 12:34
@fnocetti Thanks for looking at this.
I can reproduce this also in the reset password process.


The error messages in the console:
![image](https://github.com/huridocs/uwazi/assets/102693686/95f16d67-99bf-412f-a925-bba51f9df9fd)

**Comment by fnocetti** [comment] 2024-05-29 13:26
@aphilop I still can't reproduce this again.
Maybe you are reusing the links for the second tests? Can you please try the whole flow? Generating a new password reset, or creating a new user?
We tried in you instance, and I originally got the error, but after that I was able to successfully go through the flows.
I strongly suspect that this is a one time thing on the first ever try after we changed the strategy.

**Comment by aphilop** [comment] 2024-05-29 13:47
@fnocetti

I tried again the following: 
- Create a new user and then create a new password: now it works
- Reset password for the new user: now it works

I will ask the colleugues who first experienced the problem to check again and if they report also that is working, I will close the issue.

Thanks for the support!

**Comment by aphilop** [comment] 2024-05-29 14:00
The colleagues reported that this is working again. I am closing this.

**Comment by fnocetti** [comment] 2024-06-06 12:55
Closing as fixed.
For the record, the problem was that the expiration timestamp for the restore record was being set in wrong way.

**Closed as completed by fnocetti** 2024-06-06 12:55 UTC
Labels: Bug :lady_beetle:, Priority: Critical :fire:, Backend 💾
