### ISSUE TITLE
Send e-mail from a generic e-mail

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#5693] opened 2023-04-11 14:22 UTC
**Describe the bug**
emails are sent from users configured emails, this is causing the emails to go to the spam folder.

**Expected behavior**
Uwazi notifications should be sent from a generic "noreply@uwazi.io" or similar. Moreover, this variable should be configured as an env var/db config option so self hosted can set it.

It should be configurable per tenant, so people using custom domains can use noreply@theirdomain.xxx

**Comment by LaszloKecskes** [comment] 2023-04-13 09:09
@txau @RafaPolit 
While reading the backend implementation of emails for this issue, I've noticed that we already have entries for `contactEmail` and `senderEmail` on the settings. There's a mailer module in `mailer.js` that uses the sender entry to construct sender details. The default is "'no-reply@uwazi.io". In a discussion with @konzz, we have discovered, that there already was a similar issue (#3309), and you can even set this from the UI (in Settings - Collection - Forms and email configuration - Contact Form). 

As far as I can see, while this is not the implementation laid out in the discussion (it is not in the tenant definitions, and not in an environmental variable), it checks out all requirements. Namely:
 - there is a default
 - it can be set per tenant
 - self-hosted people can set it
 
My questions:
- The issue mentions that "emails are sent from users configured emails, this is causing the emails to go to the spam folder". The emails I found use this. There could be others that do not go through this module, then we should fix that as a critical issue. Can you supply specific examples of what emails are going astray?
- The ui that sets this is tied to contact forms, but it clearly affects other things as well and makes sense without the forms. We could try and move it out. Should we? I don't think this one is critical, could be a separate issue.
- Do we still want the option to overwrite this via an environmental variable? I think it is not necessary, and could go against the "per-tenant" requirement.

**Comment by vostorga** [comment] 2023-04-14 20:16
Hi Laszlo

Replying to your questions below:

>  The issue mentions that "emails are sent from users configured emails, this is causing the emails to go to the spam folder". 
> The emails I found use this. There could be others that do not go through this module, then we should fix that as a critical issue. Can you supply specific examples of what emails are going astray?

The following is the provided example going to spam, the email sender was changed to the admin user that created a new account instead of being sent from the default sender entry "'[no-reply@uwazi.io](mailto:no-reply@uwazi.io)".:
Screenshot :
![image](https://user-images.githubusercontent.com/16454565/232144290-9d2a7fea-3993-40d6-8485-26873bb2ce11.png)

> The ui that sets this is tied to contact forms, but it clearly affects other things as well and makes sense without the forms. We could try and move it out. Should we? I don't think this one is critical, could be a separate issue.

Will leave the decision to uwazi team

> Do we still want the option to overwrite this via an environmental variable? I think it is not necessary, and could go against the "per-tenant" requirement.

If the default email from address functionality is fixed, I believe new variables would be skipped

**Comment by LaszloKecskes** [comment] 2023-04-17 16:11
After checking the data, it looks like Uwazi is performing as intended: the above email address is really set in that instance as the sender email. The recipients email provider probably marks it as spam, since <admin_name>@huridocs.org does not match the domain uwazi.io, which is a common red flag. The solution would be to set the sender email from the UI to something that matches the domain.

We have agreed to have a further discussion about whether we want to organize the UI responsible for setting this in a more intuitive way.

**Comment by LaszloKecskes** [comment] 2023-04-18 15:48
Closing in favor of #5721.

As mentioned above, Uwazi is working correctly, the solution is to set the sender email to something that matches the domain it was sent from. For uwazi.io, leaving it empty for the default 'no-reply@uwazi.io' is also sufficient.

**Closed as completed by LaszloKecskes** 2023-04-18 15:48 UTC
Labels: Bug :lady_beetle:, Sprint, Priority: Critical :fire:
