### ISSUE TITLE
There are languages in settings multiple times

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#6238] opened 2023-11-06 13:45 UTC
**Describe the bug**
We detected that on some instances settings has duplicated and triplicated languages.

**To Reproduce**
We do not know how this can be reproduced

**Expected behavior**

**Additional context**
This scenario produced a migration 148 failure on the instances we had to [HOTFIX](https://github.com/huridocs/uwazi/pull/6237) it.

**Comment by RafaPolit** [comment] 2023-11-06 15:08
Maybe multiple clicks on the add / save button?

**Comment by Zasa-san** [comment] 2023-11-06 20:49
> Maybe multiple clicks on the add / save button?

The modal that triggers the install closes immediately, regardless of connection speed. However, if the installation of a language takes a long time, you can reopen the modal and install the same language again.

I was able to reproduce the issue by doing that:

![image](https://github.com/huridocs/uwazi/assets/71732018/8f850171-83ab-44eb-bfed-957c2d6e9700)

**Comment by LaszloKecskes** [comment] 2023-11-21 10:59
Summarizing the work so far:
 - the endpoint repeats not only the addition to the settings, but all steps (entity duplication, page duplication), except translations
 - the addition to the settings does not have any check, it repeats
 - the entity and page cloning does have checks implemented, but they check the obsolete `locale` property instead of the current `language`
 - the changes were missed at the time probably because all of the above is untested
 - translation is an exception, because it was tested properly and indeed worked correctly

The issue is going to be addressed in two parts:
 - a hotfix for the endpoint, directly to prod, to prevent further issues
 - a migration to remove duplicated entries from settings, pages and entities. We've double checked the data on production, and luckily, there's only negligible impact, so we can move with our normal release schedule for the migration.

**Closed as completed** 2023-11-24 16:37 UTC
Labels: Bug :lady_beetle:, Priority: High, Backend 💾
