### ISSUE TITLE
Inheriting select properties does not bring translated thesauri values

### ISSUE THREAD

**Issue by hyebin-bina** [huridocs/uwazidocs#7259] opened 2024-09-23 12:38 UTC
**Describe the bug**
When users inherit a select property from another template, even when relevant thesaurus is fully translated, translated values do not come through.

**To Reproduce**
1. Create template A with a select property. 
2. Translate thesaurus values attached to the select property in another language.
![Screenshot 2024-09-23 at 9 34 59 PM](https://github.com/user-attachments/assets/e858f8d5-bc0b-4a13-a75c-f3317073eccd)
![Screenshot 2024-09-23 at 9 34 08 PM](https://github.com/user-attachments/assets/b6373c7d-8cdb-4822-bfc8-17bb7b605d04)

4. Create and populate an entity in template A.
5. Create template B with a relationship property, inheriting the single property of template A created in step 1. Check "use as filter" for better visibility. 
6. Go to the library, create an entity in template B, inheriting select property of the entity created in step 3.
7. Switch the interface in another language. 
8. Check the inherited values on the side panel and confirm the inherited values are displayed in English in other language interfaces, even after translating the thesauri values.
![Screenshot 2024-09-23 at 9 33 09 PM](https://github.com/user-attachments/assets/e2e3a707-c583-4ef3-9e93-6c190af1e2ac)

**Expected behavior**
When inheriting select properties, corresponding thesauri's translations should be inherited.

cc: @LuGomezV @salvalacruz

**Comment by txau** [comment] 2024-09-23 15:46
This may be the same or related to:

https://github.com/huridocs/uwazi/issues/7184
https://github.com/huridocs/uwazi/issues/7183

**Comment by RafaPolit** [comment] 2024-11-27 21:30
The above report and ways to reproduce is 100% correct.

After research, the bug is NOT on the denormalized data, which is working as expected.  The problem is just on the filters for inherited properties.  "Root selects" do respect the translation, but this is apparently being done in the Front End, as the backend is sending always the base property name.  So I believe this is a frontend issue. cc @konzz

**Comment by aphilop** [comment] 2024-12-04 13:49
@txau I assume you closed that accidentally.
This is not done and the frontend committed to fix this in this sprint.
I reopen this.

**Comment by txau** [comment] 2024-12-04 13:51
@aphilop I think that was an accidental drag and drop while using GitHub on mobile. It is pretty glitchy. Thanks for spotting that

**Closed as completed** 2024-12-18 13:14 UTC
Labels: Bug :lady_beetle:, Priority: High, Frontend :sunglasses:
