### ISSUE TITLE
Wrong file name parsing due to missing extension

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#7135] opened 2024-08-20 17:17 UTC
We are creating entries of this form:

```
"_id" : ObjectId("668c6173afac83a434cd9beb"),
    "entity" : "rnu3ljgi0df",
    "type" : "document",
    "filename" : "1720476018696wx3osn5bm4.com discussing the case",
    "originalname" : "News article from LiveLaw.com discussing the case",
    "mimetype" : "application/pdf",
```

Where the "filename" field is wrongly inferred due to 1) a missing extension in the filename? and 2) a period in the middle of the filename, wrongly using the string after the period as the file extension.

This is creating file not found errors.

Fixes?

1. Ensure this kind of entry is not created anymore
2. Check out why this is giving file not found exceptions and either fix the data or adapt the retrieve approach.

**Comment by RafaPolit** [comment] 2024-10-08 15:58
Priorities to determine extension:
- use the actual extension
- use a "known" utility to extract the actual extension (and not just split and use the last occurrence)
- if everything else fails, simply keep the 'no extension'

**Comment by Joao-vi** [comment] 2024-10-09 12:27
@RafaPolit @txau 

Hey everyone, could someone help me reproduce the item 2? Maybe the page where this "file not found" error is found.

Item 1 is fixed, so now on, every document created should work as expected. 

You can follow the progress right here (https://github.com/huridocs/uwazi/pull/7331)

**Comment by txau** [comment] 2024-10-09 13:50
We've been seeing this errors in our logs in the form of:

```
2024-10-08T18:02:14.894Z [cyrilla-ix-test] 
File 1682523685131ns7nb4qqq8p. Telegram not found in s3 storage
original error: {
 "filename": "1682523685131ns7nb4qqq8p. Telegram",
 "storage": "s3"
}
```

**Comment by Joao-vi** [comment] 2024-10-11 10:27
Closing this issue, you can check the fix right here (https://github.com/huridocs/uwazi/pull/7331).

I'm moving the item 2 to a separeted issue because there's no enougth information to replicate this error.

**Closed as completed by Joao-vi** 2024-10-11 10:27 UTC
Labels: Bug :lady_beetle:, Sprint, Priority: High, Backend 💾
