### ISSUE TITLE
Review dependabot strategy

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#7113] opened 2024-08-07 15:10 UTC
Currently we have a basic configuration for dependabot that creates a number of PRs to update dependencies. 

It's creating a problem since it generates several PRs, all of them running the CI pipeline, and automatically updating every time something is merged into development. We should review our dependabot configuration to improve how this flow works.

Ideally we would like to have dependabot create a single PR grouping bumps if possible, and maybe avoid automatically updating the PR. We have some package families that we know should be updated together (react, dnd-kit, socket.io, babel), for those cases instead of having several PRs updating the related libraries we could implement dependency grouping.

Finally, we should exclude `storybook` and it's related libraries from the bumps, since it's supposed to be updated via CLI.

**Comment by txau** [comment] 2024-08-07 15:52
These options may solve the problem:

https://github.com/hrvey/combine-prs-workflow
https://github.com/github/combine-prs

**Comment by mfacar** [comment] 2024-10-24 16:41
@txau, @Zasa-san, after checking, DependaBot configuration allows having many groups through a pattern or type of versions to include a dependency into a group based on the first match. By now, we have three types of groups:
- Families of dependencies
- Minor dependencies
- Major dependencies

For whatever dependency doesn't fit in the defined groups, DependaBot will create a standalone PR to update it. 
I'm currently working on identifying the necessary exclusions to make the PRs pass without errors, ideally, there should be an issue for every excluded dependency or at least having individual PRs to solve the specific problems.

**Comment by Zasa-san** [comment] 2024-11-11 17:07
We have already a bump using this method:
https://github.com/huridocs/uwazi/pull/7435

This is a group of Major deps. It's failing but it's better than having several PRs.

I think there might be a problem with the implementation since the PR lists [@socket.io/redis-adapter](https://github.com/socketio/socket.io-redis-adapter), but the grouping in `dependabot.yml` says
```
      socket.io:
        applies-to: version-updates
        patterns:
          - socket.io*
```

I understand that anything socket.io should be excluded from major bumps, and grouped into a family bump for socket.io stuff. Is that correct @mfacar ?

**Comment by mfacar** [comment] 2024-11-26 22:25
> I understand that anything socket.io should be excluded from major bumps, and grouped into a family bump for socket.io stuff. Is that correct [@mfacar](https://github.com/mfacar) ?

@Zasa-san, Sorry I missed your mention, you're right, I updated the configuration to have a specific group for socket.io.

**Comment by mfacar** [comment] 2024-11-26 22:54
Summary of the Dependabot Strategy:

- Dependabot will create pull requests (PRs) based on the configuration of dependency groups and exclusions.
- If a PR fails, we need to identify any dependencies with breaking changes that require code modifications to work properly. In such cases, we should:
  * Create an issue using the template `Dependency update`.
  * Add the problematic dependency to the `ignore` section in `.github/dependabot.yml`, then commit this change directly to the development branch.
  * Once the issue is resolved, remove the dependency from the `ignore` section in `.github/dependabot.yml` as part of closing the issue.

The current `.github/dependabot.yml` configuration includes the following:

- An `ignore` section containing dependencies that require further review, with an issue created for each of them.
- Groups of dependencies that are updated together based on naming patterns: ```@babel*, @storybook*, @sentry*, @dnd-kit*, socket.io*, eslint-*, and express*```.
- dev-minor-dependencies, with the latest PRs successfully merged.
- dev-major-dependencies, with the latest PRs successfully merged.

cc. @Zasa-san, @RafaPolit, @konzz, @txau

**Closed as completed by mfacar** 2024-11-26 22:54 UTC
Labels: Priority: Medium, Tech Debt :hammer_and_wrench:
