### ISSUE TITLE
Comments to: Multiselct with groups or checkboxes #6672

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#6697] opened 2024-04-23 15:35 UTC
Comment from [Issue #6672 ](https://github.com/huridocs/uwazi/pull/6672)

Testing comments from the Programme Team (@Ximena25 @salvalacruz ):

NEED TO CHECK:
- When entering to a screen in Settings area, with multiple select components, the first time you click an option, the screen blinks suddenly.
- Whe accesing a long list of options (i.e. a Thesauri with multiple items), if you scroll down and click on an item at the bottom, the screen suddenly goes up to the top of the items.
- In the /settings/thesauri screen, is not allowed to select any thesauri (before deleting it). "Select all" does not work too.

**Comment by RafaPolit** [comment] 2024-04-26 15:17
Thanks for this QA! Very useful:

- We cannot reproduce this first item, can you please expand on how to reproduce the problem?
- Indeed, any interaction with the checkboxes past the top-scroll point simply jumps back to the top of the page.  It may be that the table component is fully unmounting, losing context of the scroll size.
- This is mostly "expected" as you cannot delete Thesaurus being used in templates, but it's utterly unclear for the user why this boxes are disabled.  We should find a better way to report to the user that the Thesaurus is being used. Also, not sure if disabling the checkbox is the right way, since there could be more options than just "Delete". cc @juanmnl

**Comment by salvalacruz** [comment] 2024-04-26 16:02
Hi @RafaPolit ,

I've just tried to repdroduce the first scenary to explain it better, but now it is worst:

Please try from https://cejil-staging.uwazi.io/en/settings/thesauri or from https://cejil-staging.uwazi.io/en/settings/relationship-types
Right now, when trying to click on any checkbox, the UI does not allow it.

**Comment by salvalacruz** [comment] 2024-04-26 16:10
> I've just tried to repdroduce the first scenary to explain it better, but now it is worst:
> 
> Please try from https://cejil-staging.uwazi.io/en/settings/thesauri or from https://cejil-staging.uwazi.io/en/settings/relationship-types Right now, when trying to click on any checkbox, the UI does not allow it.

Now I see this is expeted, thank you.

**Comment by salvalacruz** [comment] 2024-04-26 16:11
About the blink, please try in https://cejil-staging.uwazi.io/en/settings/pages 

When selecting  items by clicking the checkbox, sometimes you get a blink in the screen, sometimes not.

**Comment by aphilop** [comment] 2024-07-15 21:03
@salvalacruz @Ximena25 

>When entering to a screen in Settings area, with multiple select components, the first time you click an option, the screen blinks suddenly.

I cannot reproduce this in https://right.staging.uwazi.io/en/settings/pages
Can you check if this is still an issue and if possible provide me access to cejil.staging to be able to test it?

>When accesing a long list of options (i.e. a Thesauri with multiple items), if you scroll down and click on an item at the bottom, the screen suddenly goes up to the top of the items.

This will be resolved with https://github.com/huridocs/uwazi/issues/6780

>In the /settings/thesauri screen, is not allowed to select any thesauri (before deleting it). "Select all" does not work too

This is a usability problem and I am going to check if it is already reported otherwise I'll open a separate issue to handle this.

**Comment by salvalacruz** [comment] 2024-07-15 21:13
> Can you check if this is still an issue and if possible provide me access to cejil.staging to be able to test it?

I've just created a user for you.

**Comment by aphilop** [comment] 2024-07-15 21:25
Thank you @salvalacruz 

I just tested with Safari and Firefox and cannot see any blink in the screen when selecting items in https://cejil.staging.uwazi.io/es/settings/pages

If someone can reproduce this, it would be very helpful.
Otherwise, I would suggest to close the issue as the other problems will be handled as described in my previous comment.

**Comment by salvalacruz** [comment] 2024-07-15 21:28
Hi, it still happens to me in Firefox and Brave, we can try together if you want.

**Comment by aphilop** [comment] 2024-07-17 19:59
After talking with @salvalacruz, we assume that the observed problem will be resolved with #6780.
We'll check again after table changes go live to verify that the problem is solved.

**Comment by RafaPolit** [comment] 2024-08-16 14:44
Confirm if these behaviors are fixed with @mfacar 's development on Thesaurus.

**Comment by mfacar** [comment] 2024-08-22 21:16
#7132 solves most of the problems related to Thesauri, except the mechanism to forbid a used thesaurus, the checkbox is still disabled, an alternative could be to show the Remove button and inform the user of the items used that couldn't be deleted, similar to the current behavior of templates. cc. @juanmnl 
#7131 will cover the other points reported. cc. @Zasa-san

**Comment by aphilop** [comment] 2024-09-12 06:47
The bugs reported in this issue are now solved.
The issue with the disabled checkboxes needs a proper design solution and will be handled first with https://github.com/huridocs/uwazi-design/issues/32

**Closed as completed by aphilop** 2024-09-12 06:47 UTC
Labels: Bug :lady_beetle:, Priority: High
