### ISSUE TITLE
Flaky test e2e/regression_suites/entities.test.ts

### ISSUE THREAD

**Issue by LaszloKecskes** [huridocs/uwazidocs#5394] opened 2022-12-09 10:08 UTC
The above test is failing a lot on the CI, then gets resolved on re-runs. It is a regression test, that shows 25% difference on failing runs, which is another reason that points towards flakiness. Here is an example failing output:

```
FAIL e2e/regression_suites/entities.test.ts (22.193 s)
  Homepage entities
    ✓ should display entities in homepage (1106 ms)
    ✓ should display entity details (1159 ms)
    ✕ should display relationships on the sidepanel (918 ms)
    ✓ should display entity view page (1733 ms)
    ✓ should display entity edit page (1624 ms)
    ✓ should display entity relationship page (24[70](https://github.com/huridocs/uwazi/actions/runs/3656298858/jobs/6178581654#step:15:71) ms)

  ● Homepage entities › should display relationships on the sidepanel

    Expected image to match or be a close match to snapshot but was 25.07042[72](https://github.com/huridocs/uwazi/actions/runs/3656298858/jobs/6178581654#step:15:73)36315084% different from snapshot ([75](https://github.com/huridocs/uwazi/actions/runs/3656298858/jobs/6178581654#step:15:76)111 differing pixels).
    See diff for details: /home/runner/work/uwazi/uwazi/e2e/regression_suites/__image_snapshots__/__diff_output__/entities-test-ts-homepage-entities-should-display-relationships-on-the-sidepanel-1-snap-diff.png

      58 |   const screenshot = await element.screenshot(screenshotOptions);
      59 |
    > 60 |   expect(screenshot).toMatchImageSnapshot({
         |                      ^
      61 |     failureThreshold: options.threshold || DEFAULT_IMAGE_REGRESSION_THRESHOLD,
      62 |     failureThresholdType: 'percent',
      63 |     allowSizeMismatch: true,

      at testSelectorShot (helpers/regression.ts:60:22)
      at async Object.<anonymous> (regression_suites/entities.test.ts:33:5)
```

**Comment by grafitto** [comment] 2023-04-18 13:07
This issue is a duplicate of https://github.com/huridocs/uwazi/issues/5470 and the discussion should be on the linked issue

**Closed as completed by grafitto** 2023-04-18 13:07 UTC
Labels: Priority: High, Tech Debt :hammer_and_wrench:, Frontend :sunglasses:
