### ISSUE TITLE
Installing Uwazi on Debian 10 (Buster)

### ISSUE THREAD

**Issue by enrroquez** [huridocs/uwazidocs#5658] opened 2023-04-03 02:24 UTC
Hi, dear Uwazi development team.

I have tried to do the installation and found problems I could not solve with the documentation available [here](https://github.com/huridocs/uwazi#dependencies), [here](https://github.com/huridocs/uwazi/blob/development/SELF_HOSTED_INSTRUCTIONS.md) and [here](https://uwazi.readthedocs.io/_/downloads/en/latest/pdf/).

The versions of the installed dependencies are:
1. NodeJs 18.15.0 and nvm 9.5.0
2. ElasticSearch 7.17.6 (Optional - Disable ml module in the ElasticSearch - PENDING))
3. ICU Analysis Plugin (Optional - Installation - PENDING)
4. MongoDB 4.2.24
5. Yarn 1.22.19
6. poppler-utils 0.71.0-5 (pdftotext)

[The following descripton](https://github.com/huridocs/uwazi/blob/development/SELF_HOSTED_INSTRUCTIONS.md) is confusing to me, and there is no clarification in the other sources I found:
"From within uwazi/latest, create a blank state with the desired database name. The platform deafults to uwazi_development if you don't define any name.`NODE_ENV=production yarn blank-state my_db_name`"

The steps I took were:
```
# yarn install > which resulted in lots of warnings over unmet dependencies (please see the corresponding attached file)
# export NODE_ENV=production
# export DATABASE_NAME=uwazi_development
# export INDEX_NAME=uwazi_development
# export FILES_ROOT_PATH=/var/uwazi/latest
# yarn blank-state uwazi_development > which generated connection errors with the database (please see attachments)
```

and finally tried to run the server
`# node server.js > (please see attachments to see the output)`

Hope you could give me a hand or point me in the right direction.

Thanks for all the work you do for the improvement of this great HFOSS.
Best
Enrique

Attachments:
* [yarn_install.txt](https://github.com/huridocs/uwazi/files/11134170/yarn_install.txt)
* [yarn_blank-state_uwazi_development.txt](https://github.com/huridocs/uwazi/files/11134168/yarn_blank-state_uwazi_development.txt)
* [node_server.js.txt](https://github.com/huridocs/uwazi/files/11134167/node_server.js.txt)

**Comment by RafaPolit** [comment] 2023-04-03 16:26
Thanks for the detailed report.  Let's try to figure this out, hopefully with as little complication as possible.

First of all, thanks for pointing out the not-so-clear aspects of the documentation.  It's very much an on-going process and we aim to improve it.

Two things that may not be clear from the instructions:
- When we request `node >= 16.17.0`, this is in case Node releases a 16.17.03, not that it is tested with anything higher than v16, so please, to ensure the latest Node version we support: remove the node modules (just in case) and then use the requested version by: `nvm use` within the `wazi/lastest` folder.  This will probably request you to download the supported node version, go ahead and follow the onscreen instructions until you are working with that particular node version.  If you are only running Uwazi, make that your default version.  If you are using this machine for other things, remember to always start any process with `nvm use` in order to ensure the right version
- The confusing part of "create a blank state" is precisely what you did: is just ensuring that the folder structure is correct (with the newly created folders) and run `yarn blank-state` inside that folder with the proper node exports regarding environment and database names.

That said, what appears to be the problem is that your Mongo server somehow crashed between the restoring of the blank-state and the subsequent migration.  

We have seen this happen on systems that are very near or below certain specs, especially memory.  How much ram does your system have and how much of it has been allocated for Elastic Search?  ES can be a true memory hog, so if you have 2GB and below, it may be useful to limit ES to 512Mb for the time being until we figure out what else may have gone wrong.

One final comment, while the ICU plugin is listed as optional, we had at one point implementations that simply "assumed" it's there, so maybe install that as a first step to avoid further complications.

Thanks again for the detailed report, we will try to make the instructions a bit clearer with this feedback.

Don't hesitate to write back with any doubts or future problems.

**Comment by enrroquez** [comment] 2023-04-03 22:10
Thanks a lot Rafa.

Our system complies with [the minimum requirements](https://github.com/huridocs/uwazi/issues/5216): it has two Processors: 2 x 2.4 GHz, Memory: 4096 MB, Storage: 40 GB and is aimed to run Uwazi exclusively.
I have noticed from @txau advice there and from yours here, the concern about resources, and certainly this system will need some tune up considering that after all the steps I will describe below it is using 3600 MB (88%) of the RAM available. I hope we could improve that later.

In the other hand, it looks like those problems I described before were solved ...and new one pop up. I will document here the process, hoping it is useful to others .

### Install the missing Elasticsearch plugin ICU analysis
`root@4kbv:/var/uwazi/latest# /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu`
Which tells me at the end of the process: _Installed analysis-icu_ and asks to restart Elasticsearch
In case people does not find the plugin manager in the same path, documentation that explains [the directory layout can be found here](https://www.elastic.co/guide/en/elasticsearch/plugins/current/plugin-management.html).

### Restart Elasticsearch
`root@4kbv:/var/uwazi/latest# systemctl restart elasticsearch.service `
### List the versions available of node runtime environment
`root@4kbv:/var/uwazi/latest# nvm ls-remote`
### Install the right version of node
`root@4kbv:/var/uwazi/latest# nvm install 16.17.1`
_...as 16.17.2 was not available_
### Check the versions of node installed in the system
`root@4kbv:/var/uwazi/latest# nvm ls`
### Uninstall the version that is left over
`root@4kbv:/var/uwazi/latest# nvm uninstall 18.15.0`
### Set version 16.17.1 as the default
`root@4kbv:/var/uwazi/latest# nvm alias default 16.17.1`
_...just to be sure_
### Install yarn package manager
`root@4kbv:/var/uwazi/latest# npm install --global yarn`
### Install packages included in package.json
`root@4kbv:/var/uwazi/latest# yarn install`
please [see output](https://github.com/huridocs/uwazi/files/11142155/yarn_install2.txt), it shows warnings of different kind
### Set up environment variables
```
root@4kbv:/var/uwazi/latest# export NODE_ENV=production
root@4kbv:/var/uwazi/latest# export DATABASE_NAME=uwazi_development
root@4kbv:/var/uwazi/latest# export INDEX_NAME=uwazi_development
root@4kbv:/var/uwazi/latest# export FILES_ROOT_PATH=/var/uwazi/latest
```
### Run the blank-state script indicating the database name
`root@4kbv:/var/uwazi/latest# yarn blank-state uwazi_development`
This is [the output](https://github.com/huridocs/uwazi/files/11142224/yarn_blank_state2.txt), which looks clean to me.
### Check whether MongoDB is still active
`root@4kbv:/var/uwazi/latest# systemctl status mongod`
_...and it is still up and running_

At this point I wonder if the installation was completely successful or if there are (minor) issues I should take care of.

### Tried running the Express server ...and found a new error
```
root@4kbv:/var/uwazi/latest# node server.js
Connecting to mongodb://localhost/
🌎 Listening on port 3000. Open up http://localhost:3000/ in your browser.
2023-04-03T19:06:20.522Z [uwazi_development] requestId: 3350 
```
It looks like I got somewhere ;-), but when I tried to reach the web interface, in the browser I got error messages in json format:
`{"error":"(0 , _router.unstable_createStaticHandler) is not a function","prettyMessage":"(0 , _router.unstable_createStaticHandler) is not a function","requestId":5674}`

the terminal shows in standard output:
```2023-04-03T19:06:20.522Z [uwazi_development] requestId: 3350 
url: /login
TypeError: (0 , _router.unstable_createStaticHandler) is not a function
    at getSSRProperties (/var/uwazi/latest/app/react/entry-server.js:233:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async EntryServer (/var/uwazi/latest/app/react/entry-server.js:257:55)
    at async /var/uwazi/latest/app/api/utils/routesErrorHandler.js:7:5
original error: {}
```
And when I shutdown the Express server using CTRL-C, the server reports:
```
^CSIGINT signal received.
Gracefully closing express connections
Disconnected from database
Server closed succesfully
root@4kbv:/var/uwazi/latest#
```
Is there something else I should do about the warnings shown when installing the packages with `yarn install`?
Tomorrow I will try to find out more about the _router.unstable_createStaticHandler error and come back here.
Thanks!

**Comment by enrroquez** [comment] 2023-04-04 23:20
Hi Rafa!, I have found createStaticHandler is a React Router, and it looks like this is an error handling middleware with this router. Am I right?, could it be a bug in the code?

**Comment by enrroquez** [comment] 2023-04-16 01:36
With a helping hand of a friend, we have found that the cause of the problem was the [React Router](https://github.com/remix-run/react-router) dependency version defined in [package.json](https://github.com/huridocs/uwazi/blob/development/package.json) `"@remix-run/router": "^1.4.0",`

We have downgraded npm package to version 1.0.4 `"@remix-run/router": "1.4.0",` and I wonder how sustainable this dependency can be as the current version of the [React Pouter package is 6.10.0](https://github.com/remix-run/react-router/releases)?

That fixed the issue and made the system run, but we had to take some additional steps:

1. We have [added 8g of swap](https://linuxize.com/post/create-a-linux-swap-file)
2. For elasticsearch we have [configured jvm ram usage to 2g](https://www.elastic.co/guide/en/elasticsearch/reference/7.11/jvm-options.html) (-Xmx2g -Xmxs2g)
3. And pumped the [timeout lapse of the systemd service to 4 minutes](https://blog.sleeplessbeastie.eu/2020/02/29/how-to-prevent-systemd-service-start-operation-from-timing-out)

We would appreciate your comments and support.

**Comment by RafaPolit** [comment] 2023-04-20 13:38
Hello @enrroquez 

The swap config and ram usage for ES make a lot of sense to me.  The timeout lapse I am not sure why it was needed.  What was hanging for longer?  The requests? The spool up porcess?

About the remix router, let me reach out to our front end team that have been updating react router to see what they think about this.

cc @mfacar @Zasa-san

**Comment by mfacar** [comment] 2023-04-20 14:20
Hello @enrroquez, @RafaPolit 

The release [1.112.0](https://github.com/huridocs/uwazi/releases/tag/1.112.0) upgrades @remix-run/router to 1.4.0.  In this version, they've replaced the unstable_createStaticHandler with createStaticHandler. @enrroquez can you please try to install this release and check? We are depending on some functionality of this package and it is important to have it updated.

**Comment by RafaPolit** [comment] 2023-06-23 14:38
Since there are no replies, I'm closing this issue.  Feel free to reopen a new one if the problem is still there.

**Closed as completed by RafaPolit** 2023-06-23 14:38 UTC
Labels: Support
