### ISSUE TITLE
Translated label doesn't appear on uwazi instance (but correctly translated/available in settings)

### ISSUE THREAD

**Issue by verobellin** [huridocs/uwazidocs#7340] opened 2024-10-11 07:15 UTC
We have a few labels that in the Arabic version of our uwazi instance appear in English despite being translated correctly into Arabic in the settings. I checked this a couple of times in the thesaurus, templates and related translation sections of the settings but no matter what I do (re-translate it, re-save it, etc) it continues to appear in english. I have attached a two screenshots of the issue concerning one of the label - the same issue appears with other labels as well, while with others everything is fine. 
![xxx](https://github.com/user-attachments/assets/a414457e-8d0a-435d-85f7-18267bf02d88)
![xxxxxxxx](https://github.com/user-attachments/assets/be867a79-9dfe-4bd1-9cf3-e71f4b6bbc2e)

**Comment by aphilop** [comment] 2024-10-11 21:57
Hi @verobellin 
Thank you for your message. To be able to support you with this problem, can you please provide some additional information:
- Is this about a self-hosted instance or one hosted at uwazi.io?
- You said this issue appears with some labels, while with others everything is fine. What kind of labels don't get translated? Is there any other commonality among them or any other difference to the ones that get translated?
- Have you tried to use the `Live translate` feature (accessible through the language selection drop/down menu) and see if you could translate these labels?

**Comment by RafaPolit** [comment] 2024-10-18 14:37
This may happen when a filter is actually pulling data from two different sources.  For example, two templates have the Perpetrators label.  It should be translated in all, but there is a chance that the translator is looking into the wrong one when creating the final text.

**Comment by Malove98** [comment] 2024-10-23 22:55
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by aphilop** [comment] 2024-11-25 19:36
@verobellin 
Are you still facing this problem or can we close this issue?
If the problem is not resolved can you please provide the information requested above to be able to further support you with this? Thanks

**Comment by aphilop** [comment] 2024-12-02 17:19
Since there is no feedback, I am closing this.
Please reopen if needed, thanks.

**Closed as completed by aphilop** 2024-12-02 17:19 UTC
Labels: Support
